[workspace]
members = [
  "crypto/transcript",

  "crypto/dalek-ff-group",
  "crypto/tables",
  "crypto/multiexp",

  "crypto/dleq",
  "crypto/frost",

  "coins/monero",

  "processor",

  "substrate/runtime",
  "substrate/consensus",
  "substrate/node"
]

[profile.release]
panic = "unwind"
