[package]
name = "serai-processor"
version = "0.1.0"
description = "Multichain processor premised on canonicity to reach distributed consensus automatically"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/processor"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2021"
publish = false

[[bin]]
name = "serai-processor"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# Macros
async-trait = "0.1"
thiserror = "1"
rand_core = "0.6"
chrono = "0.4.0"
clap = "2.18.0"
log = "0.4.8"
futures-executor = { version = "0.3.0", optional = true }
futures-util = { version = "0.3.0", default-features = false }
calloop = "0.10.1"
libp2p = "0.48.0"
timer = "0.2.0"
libc = "0.2.134"
config = "0.13.1"
warp = "0.2"
async-std = { version = "1.9.0", features = ["attributes"] }
backoff = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Cryptography
group = "0.12"
zeroize = { version = "1.5", features = ["zeroize_derive"] }
zalloc = { path = "../common/zalloc" }

curve25519-dalek = { version = "3", features = ["std"] }
dalek-ff-group = { path = "../crypto/dalek-ff-group" }

transcript = { package = "flexible-transcript", path = "../crypto/transcript" }
frost = { package = "modular-frost", path = "../crypto/frost", features = ["secp256k1", "ed25519"] }

# Monero
monero-serai = { path = "../coins/monero", features = ["multisig"] }
bitcoin-serai = { path = "../coins/bitcoin" }

k256 = { version = "0.11", features = ["arithmetic"] }
bitcoin = "0.29"
hex = "0.4"
secp256k1 = { version = "0.24", features = ["global-context", "rand-std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

hex = "0.4"
message-box = { path = "../common/message-box" }
rdkafka = "0.28.0"

env_logger = "0.9.0"
rand = "0.3.15"
regex = "1.1.6"
smol = "1.2.4"
tokio = { version = "1", features = ["full"] }
env_perm = "0.1.3"

ciphersuite = { path = "../crypto/ciphersuite", version = "0.1", features = ["std"] }
subtle = "2"
chacha20 = { version = "0.9", features = ["zeroize"] }
multiexp = { path = "../crypto/multiexp", version = "0.2", features = ["batch"] }
schnorr = { package = "schnorr-signatures", path = "../crypto/schnorr", version = "0.2" }
dleq = { path = "../crypto/dleq", version = "0.2", features = ["serialize"] }
dkg = { path = "../crypto/dkg" }

[dev-dependencies]
rand_core = "0.6"

hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

futures = "0.3"
tokio-test = "*"

frost = { package = "modular-frost", path = "../crypto/frost", features = ["tests"] }
