version: "3.9"
name: serai-dev
  # ------------------------------------------------------------
  # Services
  # ------------------------------------------------------------
  # Profiles:
  # base - single node, unidentified
  # coins - node clients for coins only (BTC, ETH, XMR)
  # cluster-sm - Alice, Bob, Charlie
  # cluster-coins-sm - cluster-sm with coins
  # cluster-lg - Alice, Bob, Charlie, Dave, Eve, Ferdie
  # cluster-coins-lg - cluster-lg with coins
  # monero - full node monero only
  # bitcoin - full node bitcoin only
  # ethereum - full node ethereum only
  # Example: docker compose --profile bitcoin up
volumes:
  serai-base:
  serai-alice:
  serai-bob:
  serai-charlie:
  serai-dave:
  serai-eve:
  serai-ferdie:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local


services:

  _serai:
    &serai_defaults
    restart: unless-stopped
    image: serai:dev
    profiles:
      - _
    build:
      context: ../
      dockerfile: ./deploy/serai/Dockerfile
      args:
        TAG: serai
    entrypoint: /scripts/entry-dev.sh

  serai-base:
    <<: *serai_defaults
    hostname: serai-base
    profiles:
      - base
    environment:
      CHAIN: dev
      NAME: base

  serai-alice:
    <<: *serai_defaults
    hostname: serai-alice
    profiles:
      - alice
      - cluster-sm
      - cluster-coins-sm
      - cluster-lg
      - cluster-coins-lg
    environment:
      CHAIN: dev
      NAME: Alice
      VALIDATOR: true

  serai-bob:
    <<: *serai_defaults
    hostname: serai-bob
    profiles:
      - bob
      - cluster-sm
      - cluster-coins-sm
      - cluster-lg
      - cluster-coins-lg
    environment:
      CHAIN: dev
      NAME: Bob

  serai-charlie:
    <<: *serai_defaults
    hostname: serai-charlie
    profiles:
      - charlie
      - cluster-sm
      - cluster-coins-sm
      - cluster-lg
      - cluster-coins-lg
    environment:
      CHAIN: dev
      NAME: Charlie

  serai-dave:
    <<: *serai_defaults
    hostname: serai-dave
    profiles:
      - dave
      - cluster-lg
      - cluster-coins-lg
    environment:
      CHAIN: dev
      NAME: Dave

  serai-eve:
    <<: *serai_defaults
    hostname: serai-eve
    profiles:
      - eve
      - cluster-lg
      - cluster-coins-lg
    environment:
      CHAIN: dev
      NAME: Eve

  serai-ferdie:
    <<: *serai_defaults
    hostname: serai-ferdie
    profiles:
      - ferdie
      - cluster-lg
      - cluster-coins-lg
    environment:
      CHAIN: dev
      NAME: Ferdie
      
  # Coordinator Services
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    profiles:
      - kafka
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.2
    profiles:
      - kafka
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    profiles:
      - kafka
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181

  # Processor Services

  # Coin Services
  bitcoin:
    profiles:
      - single-coins
      - cluster-coins-sm
      - cluster-coins-lg
      - coins
      - bitcoin
    build:
      context: ./coins/bitcoin/
    restart: unless-stopped
    volumes:
      - "./coins/bitcoin/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh

  ethereum:
    profiles:
      - single-coins
      - cluster-coins-sm
      - cluster-coins-lg
      - coins
      - ethereum
    build:
      context: ./coins/ethereum/
    restart: unless-stopped
    volumes:
      - "./coins/ethereum/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh

  monero:
    profiles:
      - single-coins
      - cluster-coins-sm
      - cluster-coins-lg
      - coins
      - monero
    build:
      context: ./coins/monero/
    restart: unless-stopped
    volumes:
      - "./coins/monero/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh
