[core]
host = "0.0.0.0"
port = "1337"
log_filter = "info"

[chains]
btc = true
btc_rpc = ""
eth = true
eth_rpc = ""
xmr = true
xmr_rpc = ""

[health]
logger = "debug"

[kafka]
host = "localhost"
port = "9094"
offset_reset = "smallest"
