[package]
name = "coordinator"
version = "0.1.0"
description = "Coordinates all non-consensus activities in the Serai network"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/coordinator"
keywords = []
edition = "2021"
publish = false

[[bin]]
name = "coordinator"

[dependencies]
chrono = "0.4"

hex = "0.4"
serde = { version = "1", features = ["derive"] }
bincode = "1"
serde_json = "1"

group = "0.12"
message-box = { path = "../common/message-box" }

subxt = { git = "https://github.com/paritytech/subxt.git", rev = "d41f6574174d0a7d35ffcc6c3ff4d3740f5251ec" }
dns-lookup = "1"
libp2p = "0.45"
rdkafka = "0.28"

futures = "0.3"
tokio = { version = "1", features = ["full"] }

clap = "2"
config = "0.13"
log = "0.4"
env_logger = "0.9"
