[package]
name = "serai-coordinator"
version = "0.0.1"
description = "Coordinates all non-consensus activities in the Serai network"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/coordinator"
keywords = []
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1.57"
thiserror = "1"


hex = "0.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.24"
chrono = "0.4.0"
clap = "2.18.0"
log = "0.4.8"
futures-channel = "0.3.0"
futures-executor = { version = "0.3.0", optional = true }
futures-util = { version = "0.3.0", default-features = false }
tokio = { version = "1.21.2", features = ["full"] }
calloop = "0.10.1"
libp2p = "0.48.0"
timer = "0.2.0"
rdkafka = "0.28.0"
libc = "0.2.134"
config = "0.13.1"
warp = "0.2"
lazy_static = "1.4"

async-std = { version = "1.9.0", features = ["attributes"] }
backoff = "0.1.5"

env_logger = "0.9.0"
rand = "0.3.15"
regex = "1.1.6"
smol = "1.2.4"

message-box = { path = "../common/message-box" }
dalek-ff-group = { path = "../crypto/dalek-ff-group" }

group = "0.12"
zeroize = { version = "1.5", features = ["zeroize_derive"] }
zalloc = { path = "../common/zalloc" }

[workspace]
