[core]
host = "0.0.0.0"
port = "1337"

[chains]
btc = true
btc_rpc = ""
eth = true
eth_rpc = ""
xmr = true
xmr_rpc = ""

[health]
logger = "debug"

[observer]
target_host = "127.0.0.1"
target_port = "1337"

[kafka]
server = "localhost:9094"
