[package]
name = "message-box"
version = "0.1.0"
description = "Message encryption and authentication wrapper"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/crypto/message-box"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2021"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
thiserror = "1"

rand_core = "0.6"

zeroize = { version = "1.5", features = ["zeroize_derive"] }
subtle = "2"

blake2 = "0.10"
chacha20 = { version = "0.9", features = ["zeroize"] }

group = "0.12"

transcript = { package = "flexible-transcript", path = "../transcript", features = ["recommended"], version = "^0.1.3" }
schnorr = { package = "schnorr-signatures", path = "../schnorr", version = "0.1.0" }
